// Standards
elem_gap_small: 10px
elem_gap_med: 20px

// Seiten-Struktur
section_border_radius: 3px
section_box_shadow: 0 0 15px rgba(0, 0, 0, 0.5)
section_box_shadow_inset: 0 0 15px rgba(255, 255, 255, 0.5) inset
background_color_dark: rgba(0, 0, 0, 0.8)
background_color_bright: rgba(255, 255, 255, 0.8)

// Schrift
font_family: PlayRegular
font_family_hl: PuristaSemi
font_family_h2: Purista
font_size: 14px
font_dark: #0F0F0F
font_bright: #f0f0f0
font_colored: #A81318
font_def_text_shadow: 0 0 4px #0F0F0F
font_light_text_shadow: 0 0 4px #f0f0f0
font_med_text_shadow: 0 0 4px #808080

// Formular
form_label_color: #6d6d6d
form_input_box_shadow: 0 0 4px #e5e5e5
form_input_border: 1px solid #999
form_input_border_radius: 2px
form_input_gradient_start_color: #e5e5e5
form_input_gradient_start_color_focus: #D8EBFF

// Tabelle
table_th_border: 3px solid #999
table_td_border: 1px solid #999